#!/bin/sh
set -e #u # -x for verbose logging to juju debug-log
# This must be renamed to the name of the relation. The goal here is to
# affect any change needed by the remote unit leaving the relationship.
# This script should be idempotent.
juju-log $JUJU_REMOTE_UNIT departed

BASE_INSTALL_DIR=/srv/mezzanine

if [ -d $BASE_INSTALL_DIR ]; then
    cd $BASE_INSTALL_DIR;
    cd project;
    #Lets cleanup old db data
    if [ -f juju_settings.py ]; then
        rm juju_settings.py;
    fi
fi
