#!/bin/sh
set -e #u # -x for verbose logging to juju debug-log
# This must be renamed to the name of the relation. The goal here is to
# affect any change needed by the remote unit leaving the relationship.
# This script should be idempotent.
juju-log $JUJU_REMOTE_UNIT departed
